databaseChangeLog:
  - changeSet:
      id: insert-values-into-users_roles
      author: Valentyn Sharshon
      changes:
        - insert:
            tableName: users_roles
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email = 'admin@email.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name = 'ROLE_ADMIN')
        - insert:
            tableName: users_roles
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email = 'manager@email.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name = 'ROLE_MANAGER')
        - insert:
            tableName: users_roles
            columns:
              - column:
                  name: user_id
                  valueComputed: (SELECT id FROM users WHERE email = 'user@email.com')
              - column:
                  name: role_id
                  valueComputed: (SELECT id FROM roles WHERE name = 'ROLE_USER')
